// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlite3

import (
	"time"
)

type Interval struct {
	ID              int64
	StartTime       time.Time
	PlannedDuration int64
	ActualDuration  int64
	Category        string
	State           int64
}
